import fs from 'node:fs'

/** Remplace uniquement les valeurs feuille (chaînes), pas les clés. */
const pairs = [
  ['Chargement…', 'Cargando…'],
  ['Chargement des matchs…', 'Cargando partidos…'],
  ['Chargement du profil…', 'Cargando perfil…'],
  ['Enregistrer', 'Guardar'],
  ['Enregistrement…', 'Guardando…'],
  ['Retour', 'Volver'],
  ['Rechercher', 'Buscar'],
  ['Réinitialiser', 'Restablecer'],
  ['Envoyer', 'Enviar'],
  ['Envoi…', 'Enviando…'],
  ['Fermer', 'Cerrar'],
  ['Copier', 'Copiar'],
  ['Copié !', '¡Copiado!'],
  ['Inviter', 'Invitar'],
  ['Joueur', 'Jugador'],
  ['Organisateur', 'Organizador'],
  ['par joueur', 'por jugador'],
  ['Connexion', 'Iniciar sesión'],
  ['Inscription', 'Registro'],
  ['Déconnexion', 'Cerrar sesión'],
  ['Connecte-toi', 'Inicia sesión'],
  ['Mot de passe', 'Contraseña'],
  ['Pseudo', 'Apodo'],
  ['Âge', 'Edad'],
  ['Taille (cm)', 'Altura (cm)'],
  ['Poids (kg)', 'Peso (kg)'],
  ['Date', 'Fecha'],
  ['Heure', 'Hora'],
  ['Nom', 'Nombre'],
  ['Adresse', 'Dirección'],
  ['Buts', 'Goles'],
  ['Passes', 'Asistencias'],
  ['C. jaune', 'T. amarilla'],
  ['C. rouge', 'T. roja'],
  ['Payé', 'Pagado'],
  ['Non payé', 'No pagado'],
  ['Exemple', 'Ejemplo'],
  ['Ouvert', 'Abierto'],
  ['Complet', 'Completo'],
  ["Aujourd'hui", 'Hoy'],
  ['Rejoindre', 'Unirse'],
  ['Moi', 'Yo'],
  ['Foot amateur', 'Fútbol amateur'],
  ['Mes matchs', 'Mis partidos'],
  ['Explorer', 'Explorar'],
  ['Classements', 'Clasificaciones'],
  ['Équipes', 'Equipos'],
  ['Mon profil', 'Mi perfil'],
  ['Inviter des amis', 'Invitar amigos'],
  ['Paramètres', 'Ajustes'],
  ['Créer un match', 'Crear partido'],
  ['Tes stats', 'Tus estadísticas'],
  ['Matchs joués', 'Partidos jugados'],
  ['Note moy.', 'Nota media'],
  ['Victoires', 'Victorias'],
  ['Notifications non lues', 'Notificaciones sin leer'],
  ['Configuration Supabase manquante.', 'Falta la configuración de Supabase.'],
  ['Ajoute les variables VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY, puis redeploy.', 'Añade VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY y vuelve a desplegar.'],
  ['Débutant', 'Principiante'],
  ['Confirmé', 'Confirmado'],
  ['Expert', 'Experto'],
  ['Matchs disponibles', 'Partidos disponibles'],
  ['Réserve ta place — filtre par lieu ou texte ; active « Exemples Takap » pour tester sans base remplie.', 'Reserva tu plaza — filtra por lugar o texto; activa «Ejemplos Takap» para probar sin base de datos.'],
  ["Si ce bloc n'apparaît pas après déploiement : vide le cache ou ouvre en navigation privée.", 'Si no ves este bloque tras el despliegue: vacía la caché o usa una ventana privada.'],
  ['Recherche & filtres', 'Búsqueda y filtros'],
  ['Exemples Takap', 'Ejemplos Takap'],
  ['Niveau', 'Nivel'],
  ['Par défaut tous les niveaux sont affichés. Clique à nouveau sur un niveau actif pour tout réafficher.', 'Por defecto se muestran todos los niveles. Pulsa de nuevo un nivel activo para mostrar todos.'],
  ['Rechercher un match', 'Buscar un partido'],
  ['Lieu, organisateur…', 'Lugar, organizador…'],
  ['Ville (lieu du match)', 'Ciudad (lugar del partido)'],
  ['Toutes les villes', 'Todas las ciudades'],
  ['Pour les vrais matchs, la ville est détectée dans le texte du lieu.', 'En partidos reales, la ciudad se detecta en el texto del lugar.'],
  ['résultat', 'resultado'],
  ['résultats', 'resultados'],
  ['dont ', 'incl. '],
  [' exemple', ' ejemplo'],
  [' exemples', ' ejemplos'],
  [' réel', ' real'],
  [' réels', ' reales'],
  ["Les matchs en ligne n'ont pas pu être chargés ({{error}}). Les exemples Takap ci-dessous restent disponibles.", 'No se pudieron cargar los partidos en línea ({{error}}). Los ejemplos Takap siguen disponibles abajo.'],
  ['Détail des matchs incomplet ({{detail}}). Pseudos / places peuvent être approximatifs.', 'Detalle de partidos incompleto ({{detail}}). Apodos / plazas pueden ser aproximados.'],
  ['Aucun match ne correspond à ces critères.', 'Ningún partido coincide con estos criterios.'],
  ['Élargis la recherche ou réactive les exemples Takap.', 'Amplía la búsqueda o reactiva los ejemplos Takap.'],
  ['Créer un vrai match →', 'Crear un partido real →'],
  ['Explorer la démo', 'Explorar la demo'],
  ['Annuaire joueurs', 'Directorio de jugadores'],
  ['Renseigne la date, le lieu (idéalement via Google Places) et le tarif.', 'Indica fecha, lugar (idealmente con Google Places) y precio.'],
  ['Lieu (Google Places)', 'Lugar (Google Places)'],
  ['Salle, stade, ville…', 'Pista, estadio, ciudad…'],
  ['Choisis une suggestion Google pour enregistrer le GPS (notifications à proximité).', 'Elige una sugerencia de Google para guardar el GPS (avisos cercanos).'],
  ['Niveau requis', 'Nivel requerido'],
  ["Indique le niveau attendu pour équilibrer la partie.", 'Indica el nivel esperado para equilibrar el partido.'],
  ['Prix par joueur (€)', 'Precio por jugador (€)'],
  ['Nombre max de joueurs', 'Máx. de jugadores'],
  ['Conseillé : 10.', 'Recomendado: 10.'],
  ['Publier le match', 'Publicar partido'],
  ['Création…', 'Creando…'],
  ['Nombre max de joueurs : entre 2 et 22.', 'Máximo de jugadores: entre 2 y 22.'],
  ['Prix invalide.', 'Precio no válido.'],
  ['Réponse vide du serveur.', 'Respuesta vacía del servidor.'],
  ['Match créé mais inscription organisateur impossible : {{message}}. Exécute supabase/organisateur_auto_participation.sql sur ton projet.', 'Partido creado pero falló la inscripción del organizador: {{message}}. Ejecuta supabase/organisateur_auto_participation.sql en tu proyecto.'],
  ["Sans VITE_GOOGLE_MAPS_API_KEY, saisis le lieu à la main (pas d'autocomplétion ni de GPS enregistré).", 'Sin VITE_GOOGLE_MAPS_API_KEY, escribe el lugar a mano (sin autocompletado ni GPS).'],
  ["Google Maps n'a pas pu être chargé. Vérifie la clé et les domaines autorisés.", 'No se pudo cargar Google Maps. Revisa la clave y dominios permitidos.'],
  ['Chargement du match…', 'Cargando partido…'],
  ['Récupération des infos et des participants.', 'Obteniendo información y participantes.'],
  ['Match introuvable ou inaccessible.', 'Partido no encontrado o no disponible.'],
  ['← Matchs ouverts', '← Partidos abiertos'],
  ['Terminé', 'Finalizado'],
  ['Organisateur :', 'Organizador:'],
  ['place restante', 'plaza restante'],
  ['places restantes', 'plazas restantes'],
  ['Simulation : aucun paiement en ligne.', 'Simulación: sin pago en línea.'],
  ['pour réserver.', 'para reservar.'],
  ["Tu es l'organisateur — tu ne peux pas réserver ta propre annonce.", 'Eres el organizador — no puedes reservar tu propio anuncio.'],
  ['Inviter un joueur', 'Invitar a un jugador'],
  ["Envoie une invitation : le joueur reçoit une notification. Il doit ouvrir ce match et cliquer sur « Rejoindre » pour s'inscrire — aucune place n'est réservée.", 'Envía una invitación: el jugador recibe una notificación. Debe abrir este partido y pulsar «Unirse» para inscribirse — no se reserva plaza.'],
  ["pour inviter quelqu'un (réservé à l'organisateur ou aux joueurs déjà inscrits).", 'para invitar (solo organizador o jugadores ya inscritos).'],
  ['Seuls l\'organisateur du match et les joueurs déjà inscrits peuvent envoyer une invitation. Tu n\'es pas dans ce cas pour l\'instant — inscris-toi avec « Rejoindre » ou crée ton propre match.', 'Solo el organizador y los jugadores ya inscritos pueden invitar. Aún no puedes — inscríbete con «Unirse» o crea tu partido.'],
  ['Pseudo (recherche)', 'Apodo (búsqueda)'],
  ['Au moins 2 caractères', 'Al menos 2 caracteres'],
  ['Participants ({{count}})', 'Participantes ({{count}})'],
  ["Aucun inscrit pour l'instant.", 'Nadie inscrito por ahora.'],
  ['Tu pourras cliquer « Match terminé » à partir du jour du match (date prévue).', 'Podrás pulsar «Partido finalizado» desde el día del partido.'],
  ['Match terminé', 'Partido finalizado'],
  ['Résultats du match', 'Resultados del partido'],
  ['Statistiques saisies par l’organisateur — lecture seule pour tous les participants.', 'Estadísticas del organizador — solo lectura para participantes.'],
  ['Statistiques du match', 'Estadísticas del partido'],
  ['Saisie réservée à l’organisateur : buts, passes décisives et cartons par joueur inscrit.', 'Solo organizador: goles, asistencias y tarjetas por jugador inscrito.'],
  ['Saisir les stats', 'Introducir estadísticas'],
  ['Enregistrer les stats', 'Guardar estadísticas'],
  ['Noter les joueurs', 'Valorar jugadores'],
  ['Choisis une note par joueur, puis clique sur « Valider les notes » pour enregistrer en base (table notes). Tu ne peux pas te noter toi-même.', 'Elige una nota por jugador y pulsa «Validar notas» para guardar (tabla notes). No puedes valorarte a ti mismo.'],
  ['Valider les notes', 'Validar notas'],
  ['Les notes déjà enregistrées sont rechargées depuis le serveur après validation.', 'Las notas guardadas se recargan del servidor tras validar.'],
  ["Tu étais le seul inscrit : il n'y a personne d'autre à noter pour ce match.", 'Eras el único inscrito: no hay a quién valorar.'],
  ['Les notes sont réservées aux joueurs inscrits sur ce match.', 'Las valoraciones son solo para jugadores inscritos en este partido.'],
  ['Connecte-toi pour voir ou donner des notes si tu as participé.', 'Inicia sesión para ver o dar notas si participaste.'],
  ['Place réservée (paiement simulé : non requis en V1).', 'Plaza reservada (pago simulado: no requerido en V1).'],
  ['Tu es déjà inscrit à ce match.', 'Ya estás inscrito en este partido.'],
  ['Match marqué comme terminé. Les joueurs peuvent se noter.', 'Partido marcado como finalizado. Los jugadores pueden valorarse.'],
  ['Statistiques enregistrées.', 'Estadísticas guardadas.'],
  ['Notes enregistrées !', '¡Notas guardadas!'],
  ['Sélectionne au moins une note (1 à 5 étoiles) pour un joueur.', 'Selecciona al menos una nota (1–5 estrellas) para un jugador.'],
  ['Une invitation existe déjà pour ce joueur et ce match.', 'Ya existe una invitación para este jugador y partido.'],
  ['Invitation envoyée : le joueur reçoit une notification avec un rappel — il doit cliquer sur « Rejoindre » pour s’inscrire (aucune place réservée).', 'Invitación enviada: el jugador recibe notificación — debe pulsar «Unirse» para inscribirse (sin plaza reservada).'],
  ['Chat', 'Chat'],
  ['pour voir le chat des participants.', 'para ver el chat de participantes.'],
  ['Le chat est réservé aux joueurs inscrits sur ce match.', 'El chat es solo para jugadores inscritos en este partido.'],
  ['Échanges entre participants — visible ici uniquement si tu es inscrit.', 'Mensajes entre participantes — solo si estás inscrito.'],
  ['Chargement des messages…', 'Cargando mensajes…'],
  ["Aucun message pour l'instant. Lance la discussion !", 'Aún no hay mensajes. ¡Empieza la conversación!'],
  ['Ton message…', 'Tu mensaje…'],
  ['Top joueurs', 'Top jugadores'],
  ['Note', 'Nota'],
  ['Buteur', 'Goleador'],
  ['Passeur', 'Asistente'],
  ['Par note moyenne (≥ 1 match)', 'Por nota media (≥ 1 partido)'],
  ['Total de buts (stats match enregistrées)', 'Total goles (estadísticas guardadas)'],
  ['Total de passes décisives (stats match enregistrées)', 'Total asistencias decisivas (estadísticas guardadas)'],
  ["Pas encore de données pour cet onglet.", 'Aún no hay datos en esta pestaña.'],
  ['Voir tous les joueurs →', 'Ver todos los jugadores →'],
  ['note', 'nota'],
  ['buts', 'goles'],
  ['passes', 'asistencias'],
  [' match', ' partido'],
  [' matchs', ' partidos'],
  [' match comptabilisé', ' partido contado'],
  [' matchs comptabilisés', ' partidos contados'],
  ['Mon profil', 'Mi perfil'],
  ['Statistiques et informations visibles des autres joueurs.', 'Estadísticas e información visible para otros jugadores.'],
  ['Statistiques', 'Estadísticas'],
  ['Note moyenne', 'Nota media'],
  ['Matchs joués (profil)', 'Partidos jugados (perfil)'],
  ['Total buts (stats)', 'Total goles (stats)'],
  ['Total passes (stats)', 'Total asistencias (stats)'],
  ['Matchs avec stats saisies', 'Partidos con estadísticas'],
  ['Ratio buts / match (stats)', 'Ratio goles / partido (stats)'],
  ['Rôle (base de données)', 'Rol (base de datos)'],
  ['Recharger le rôle', 'Recargar rol'],
  ['Si tu viens de passer le rôle admin en SQL, clique ici ou reconnecte-toi.', 'Si acabas de ponerte admin en SQL, pulsa aquí o vuelve a iniciar sesión.'],
  ['Les totaux « stats » viennent des feuilles de match saisies par les organisateurs après les rencontres.', 'Los totales «stats» vienen de hojas de partido introducidas por organizadores.'],
  ['Profil enregistré.', 'Perfil guardado.'],
  ["Partage ton lien d'inscription : tes amis arrivent sur Takap avec ton code (aucune API externe).", 'Comparte tu enlace de registro: tus amigos entran con tu código (sin API externa).'],
  ['Ton code', 'Tu código'],
  ['Lien à partager', 'Enlace para compartir'],
  ['Partager', 'Compartir'],
  ['📋 Copier le lien', '📋 Copiar enlace'],
  ['Rejoins-moi sur Takap Soccer pour organiser des matchs de foot !', '¡Únete a Takap Soccer para organizar partidos de fútbol!'],
  ['Rejoins-moi sur Takap Soccer', 'Únete a Takap Soccer'],
  ["Salut !\n\nJe t'invite à découvrir Takap Soccer, l'app pour organiser des matchs de foot entre amis.\n\n🔗 {{url}}\n\nÀ bientôt sur le terrain !", '¡Hola!\n\nTe invito a Takap Soccer, la app para organizar fútbol amateur con amigos.\n\n🔗 {{url}}\n\n¡Nos vemos en el campo!'],
  ['Rejoins Takap Soccer ! {{url}}', '¡Únete a Takap Soccer! {{url}}'],
  ["Je t'invite à découvrir Takap Soccer ! Rejoins-moi pour organiser des matchs de foot.", '¡Descubre Takap Soccer! Organiza partidos conmigo.'],
  ['Notifications', 'Notificaciones'],
  ['Connecte-toi pour voir tes notifications.', 'Inicia sesión para ver tus notificaciones.'],
  ['Push OneSignal en complément — touche une ligne non lue pour la marquer lue.', 'Push OneSignal además — toca una fila no leída para marcarla.'],
  ['Touche une notification non lue pour la marquer comme lue.', 'Toca una notificación no leída para marcarla.'],
  ["Aucune notification pour l'instant.", 'No hay notificaciones por ahora.'],
  ['Un joueur a créé un match.', 'Un jugador ha creado un partido.'],
  ['Tu as reçu une nouvelle note.', 'Has recibido una nueva valoración.'],
  ['Ton classement a changé.', 'Tu clasificación ha cambiado.'],
  ['Tu as été invité à un match. Ouvre le match et clique sur « Rejoindre ».', 'Has sido invitado a un partido. Ábrelo y pulsa «Unirse».'],
  ['Nouvelle activité.', 'Nueva actividad.'],
  ['Inscription enregistrée. Si une confirmation email est requise, valide-la puis connecte-toi.', 'Registro guardado. Si hace falta confirmar el email, confírmalo e inicia sesión.'],
  ['Se connecter', 'Entrar'],
  ['Connexion…', 'Iniciando sesión…'],
  ['Pas encore de compte ?', '¿Aún no tienes cuenta?'],
  ['Déjà un compte ?', '¿Ya tienes cuenta?'],
  ['Langue', 'Idioma'],
  ['Aucun joueur inscrit — sois le premier.', 'Ningún jugador inscrito — sé el primero.'],
  ['Amateur', 'Aficionado'],
]

function translateString(s) {
  let out = s
  const ordered = [...pairs].sort((a, b) => b[0].length - a[0].length)
  for (const [fr, es] of ordered) {
    if (out.includes(fr)) out = out.split(fr).join(es)
  }
  return out
}

function walk(v) {
  if (typeof v === 'string') return translateString(v)
  if (Array.isArray(v)) return v.map(walk)
  if (v && typeof v === 'object') {
    const o = {}
    for (const k of Object.keys(v)) o[k] = walk(v[k])
    return o
  }
  return v
}

const fr = JSON.parse(fs.readFileSync('src/locales/fr/translation.json', 'utf8'))
const es = walk(fr)
fs.writeFileSync('src/locales/es/translation.json', `${JSON.stringify(es, null, 2)}\n`)
